import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const SOURCE_URL = 'https://gist.githubusercontent.com/dmcb/4b67869f962e3adaa3d0f7e5ca8f4912/raw/srd-5.2-spells.json'
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const inputIndex = process.argv.indexOf('--input')

const loadSource = async () => {
  if (inputIndex >= 0 && process.argv[inputIndex + 1]) {
    return readFile(resolve(process.cwd(), process.argv[inputIndex + 1]), 'utf8')
  }
  const response = await fetch(SOURCE_URL)
  if (!response.ok) throw new Error(`Spell download failed: ${response.status} ${response.statusText}`)
  return response.text()
}

const rawText = await loadSource()
const rawSpells = JSON.parse(rawText)
if (!Array.isArray(rawSpells) || rawSpells.length < 300) {
  throw new Error('The spell source did not contain the expected SRD spell list.')
}

const cleanText = (value) => typeof value === 'string' ? value.trim() : null
const slugify = (value) => value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

const spells = rawSpells.map((spell) => ({
  slug: `srd-${slugify(spell.name)}`,
  name: cleanText(spell.name),
  level: Number(spell.level),
  school: cleanText(spell.school)?.toLowerCase(),
  classes: Array.isArray(spell.classes) ? spell.classes.map((item) => String(item).toLowerCase()) : [],
  action_type: cleanText(spell.actionType) ?? 'action',
  casting_time: cleanText(spell.castingTime),
  casting_trigger: cleanText(spell.castingTrigger),
  range: cleanText(spell.range) ?? 'Self',
  components: Array.isArray(spell.components) ? spell.components.map((item) => String(item).toLowerCase()) : [],
  material: cleanText(spell.material),
  duration: cleanText(spell.duration) ?? 'Instantaneous',
  concentration: Boolean(spell.concentration),
  ritual: Boolean(spell.ritual),
  description: cleanText(spell.description) ?? '',
  higher_level: cleanText(spell.higherLevelSlot),
  cantrip_upgrade: cleanText(spell.cantripUpgrade),
  source_type: 'srd',
  source_label: 'SRD 5.2 (2024)',
}))

const jsonOutput = resolve(root, 'public/data/spells.json')
await mkdir(dirname(jsonOutput), { recursive: true })
await writeFile(jsonOutput, `${JSON.stringify(spells, null, 2)}\n`)

const seedHeader = `-- Generated by scripts/import-spells.mjs\n-- Source: ${SOURCE_URL}\n-- Do not hand-edit; run npm run import:spells instead.\n\n`
const payload = JSON.stringify(spells).replaceAll('$spell_data$', '$spell\\_data$')
const seedSql = `${seedHeader}with imported as (\n  select value as spell\n  from jsonb_array_elements($spell_data$${payload}$spell_data$::jsonb)\n)\ninsert into public.spells (\n  slug, name, level, school, classes, action_type, casting_time, casting_trigger, range, components, material, duration, concentration, ritual, description, higher_level, cantrip_upgrade, source_type, source_label\n)\nselect\n  spell->>'slug',\n  spell->>'name',\n  (spell->>'level')::integer,\n  spell->>'school',\n  coalesce(array(select jsonb_array_elements_text(spell->'classes')), '{}'),\n  spell->>'action_type',\n  spell->>'casting_time',\n  spell->>'casting_trigger',\n  spell->>'range',\n  coalesce(array(select jsonb_array_elements_text(spell->'components')), '{}'),\n  spell->>'material',\n  spell->>'duration',\n  coalesce((spell->>'concentration')::boolean, false),\n  coalesce((spell->>'ritual')::boolean, false),\n  spell->>'description',\n  spell->>'higher_level',\n  spell->>'cantrip_upgrade',\n  'srd',\n  'SRD 5.2 (2024)'\nfrom imported\non conflict (slug) do update set\n  name = excluded.name,\n  level = excluded.level,\n  school = excluded.school,\n  classes = excluded.classes,\n  action_type = excluded.action_type,\n  casting_time = excluded.casting_time,\n  casting_trigger = excluded.casting_trigger,\n  range = excluded.range,\n  components = excluded.components,\n  material = excluded.material,\n  duration = excluded.duration,\n  concentration = excluded.concentration,\n  ritual = excluded.ritual,\n  description = excluded.description,\n  higher_level = excluded.higher_level,\n  cantrip_upgrade = excluded.cantrip_upgrade,\n  source_label = excluded.source_label,\n  updated_at = now();\n`
await writeFile(resolve(root, 'supabase/seed.sql'), seedSql)

console.log(`Imported ${spells.length} spells.`)
